---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: opsnull/helloworld:master-a000002
        args:
        - -msg=Ahoy5
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
